### ISSUE TITLE
Java SDK: Choosing an HTTP client library

### ISSUE THREAD

**Issue by booniepepper** [openfga/sdk-generator#157]
Let's get the best HTTP client library that will fit OpenFGA needs:

The primary list I'm considering is the list of `library` options from `openapi-generator`:

https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/java.md#config-options

## Features

| Library                              | JDK                 | Abstraction | NIO (Non-blocking IO) | HTTP2                       |
|--------------------------------------|---------------------|-------------|-----------------------|-----------------------------|
| [Apache HttpClient][apache-http] (5) | 7+                  | HTTP        | Yes                   | [Yes][apache-http2]         |
| [Java 11 HttpClient][java-http]      | 9+                  | HTTP        | Yes                   | Yes                         |
| [Jersey 3 ][jersey]                  | 7+                  | REST        | Yes                   | Yes* _( *requires Jetty)_   |
| [OkHttp][okhttp]                     | 8+                  | HTTP        | No                    | Yes                         |
| [OpenFeign][openfeign]               | [8+][openfeign-jdk] | HTTP        | No                    | Yes* _(* requires JDK 11+)_ |
| [Resteasy][resteasy]                 | [8+][resteasy-jdk]  | REST        | No                    | No                          |
| [Vert.x][vertx]                      | 8+                  | HTTP        | Yes                   | Yes                         |

All above support both synchronous and asynchronous execution. They also all support HTTP Header 
customization, although the REST versions tend to have more abstraction.

The following HTTP libraries are supported by the Open API generator, but are
not stand-alone projects, so are not included in the table above:

* Google API client, Spring RestTemplate, Spring WebTemplate. These are frontends that allow for pluggable HTTP backends (like Apache HTTP, or Java 11's HttpClient)
* rest-assured is a REST [wrapper over Apache HttpClient](https://github.com/rest-assured/rest-assured/blob/144a684989d4f00298cbca23c408f3d4ca9037fa/rest-assured/pom.xml#L85)
* Microprofile is a REST [wrapper over another REST library](https://github.com/eclipse/microprofile-rest-client#implementations)

Feature References:
* Links above, per project
* https://reflectoring.io/comparison-of-java-http-clients/

## Benchmarking

Benchmarking References: 
* https://dzone.com/articles/high-concurrency-http-clients-on-the-jvm
* https://www.techempower.com/benchmarks/#section=data-r21&hw=ph&test=update&p=zik0zj-qmx0qn-zik0zj-zijzb3-4fti4f&a=2

---

_Notes: The long-term support (LTS) versions of JDK today are 8, 11, 17. JDK 8 ended active
support in May 2022, but is widely used and will see security support until 2030. JDK 21 is
scheduled for release in Sept 2023._

[apache-http]: https://hc.apache.org/httpcomponents-client-5.2.x
[apache-http2]: https://httpd.apache.org/docs/2.4/howto/http2.html
[java-http]: https://openjdk.org/groups/net/httpclient/intro.html
[jersey]: https://projects.eclipse.org/projects/ee4j.jersey
[microprofile]: https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html
[okhttp]: https://square.github.io/okhttp
[openfeign]: https://github.com/OpenFeign/feign
[openfeign-jdk]: https://github.com/OpenFeign/feign#java-version-compatibility
[resteasy]: https://resteasy.dev
[resteasy-jdk]: https://resteasy.dev/2021/07/08/resteasy-4.7.0.Final/
[vertx]: https://vertx.io

**Comment by rhamzeh** [comment]
Thanks @booniepepper! May I ask you to add a column for HTTP2 support? And native HTTP Client in Java 11+?

If the native client works it would make a lot of things easier. We went that route in the Go and .NET SDKs for the sake of dropping extra production dependencies

**Comment by booniepepper** [comment]
There's a column for HTTP support already. the "native" client is the row called "Java 11 HttpClient" (Technically it's available from JDK 9 as an incubator feature)
