### ISSUE TITLE
SDKs should get the token exchange endpoint from the issuer's configuration

### ISSUE THREAD

**Issue by rhamzeh** [openfga/sdk-generator#197]
Originally reported by @stefanmilivojevic91 for the .NET SDK

> Token endpoint path should be fetched from issuer's openid configuration (.well-known/openid-configuration) endpoint. AzureAD has oauth2/token for instance and OAuth2Client is unable to fetch access token using client credentials flow

- [ ] JS SDK
- [ ] Go SDK
- [ ] Python SDK
- [ ] .NET SDK: https://github.com/openfga/dotnet-sdk/issues/30
- [ ] Java SDK

**Comment by aaguiarz** [comment]
Instead of reading it from the OpenID discovery endpoint, we can let users configure it directly, to avoid querying the endpoint.

**Comment by rhamzeh** [comment]
Duplicated by a newer issue: #238, closing in favour of that
