### ISSUE TITLE
[All SDKs] Remove `ReadAuthorizationModel` call in `BatchCheck`

### ISSUE THREAD

**Issue by rhamzeh** [openfga/sdk-generator#314]
Some (not all) SDKs call `ReadAuthorizationModel`, before checks in `BatchCheck`.

We need to remove that and replace that with better error handling where we exit early in cases of 401s instead of repeatedly calling check unnecessarily

- [x] JS SDK https://github.com/openfga/js-sdk/pull/70
- [x] Go SDK https://github.com/openfga/go-sdk/pull/78 @ewanharris 
- [x] .NET SDK
- [x] Python SDK
  - in client.py and sync client
    - remove `_check_valid_api_connection` from `BatchCheck` and `Write` (and delete the function)
    - do not ignore ApiAuthenticationError in https://github.com/openfga/python-sdk/blob/main/openfga_sdk/client/client.py#L596-L599 and https://github.com/openfga/python-sdk/blob/main/openfga_sdk/client/client.py#L413-L414
  - update tests as needed
- [x] Java SDK

**Comment by aaguiarz** [comment]
Please let's start by addressing it in the Javascript SDK

**Comment by evansims** [comment]
Python changes [shipping with 0.4.4](https://github.com/openfga/python-sdk/pull/102)
