### ISSUE TITLE
Better document how retries are handled in SDKs

### ISSUE THREAD

**Issue by aaguiarz** [openfga/sdk-generator#320]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

We need to better understand how are we retrying API calls. 

### Describe the ideal solution

Document:

- How the different retry strategies are implemented depending on the endpoint.
- How to configure the retry policy

Affected SDKs:
- [ ] JS SDK
- [ ] Go SDK
- [ ] .NET SDK
- [ ] Python SDK
- [ ] Java SDK

**Comment by ewanharris** [comment]
Closing this out as we've merged the associated PR
