### ISSUE TITLE
Java SDK: support global Context for ListObject

### ISSUE THREAD

**Issue by Didier-SimpleCommeDev** [openfga/sdk-generator#331]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

The Java `ClientListObjectsRequest` does not provide an `Object context` field, which is supported by the API, as documented in [the ReST API](https://openfga.dev/api/service#/Relationship%20Queries/ListObjects).
This is a blocking issue if any relation needs a context for evaluation.
The .Net implementation does provide this field (and seem to add it to the request body – but I’m not quite fluent in C#).

### Describe the ideal solution

The Java SDK object `ClientListObjectsRequest` offers a `context(Object context)` method and the `dev.openfga.sdk.api.client.OpenFgaClient#listObjects` adds this field to the request `body`.

### Alternatives and current workarounds

Workaround: override the OpenFgaClient, override the `listObjects` method – not tested yet

**Comment by Didier-SimpleCommeDev** [comment]
I could provide a PR if allowed by the maintainers (I don’t seem to have the rights on the repo at the moment). The code change is minor, I still have to figure out how to (unit-) test it.

**Comment by rhamzeh** [comment]
Thanks for the issues @Didier-SimpleCommeDev!

To add context you need to account for it in:
* https://github.com/openfga/sdk-generator/blob/d62eec2512d53134552c507c7fe44442be04c006/config/clients/java/template/client-OpenFgaClient.java.mustache#L656-L682
* https://github.com/openfga/sdk-generator/blob/d62eec2512d53134552c507c7fe44442be04c006/config/clients/java/template/client-ClientListObjectsRequest.java.mustache#L6-L55

As for contributing the change, we follow the normal GitHub fork and PR process, see here: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by Didier-SimpleCommeDev** [comment]
PR Pushed! 
Still in draft, something’s broken. I’ll avoid thread polution here and deal with the code-related issues in the PR comment section.
