### ISSUE TITLE
[NodeJS] README.md missing import in Client Credentials example

### ISSUE THREAD

**Issue by adriantam** [openfga/sdk-generator#392]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/sdk-generator/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/sdk-generator/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Slack Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

Example listed in https://github.com/openfga/js-sdk/blob/main/README.md#client-credentials did not work as is because CredentialsMethod is not imported.

Instead, it should read

```
const { OpenFgaClient, CredentialsMethod } = require('@openfga/sdk'); // OR import { OpenFgaClient } from '@openfga/sdk';

const fgaClient = new OpenFgaClient({
  apiUrl: process.env.FGA_API_URL, // required
  storeId: process.env.FGA_STORE_ID, // not needed when calling `CreateStore` or `ListStores`
  authorizationModelId: process.env.FGA_MODEL_ID, // Optional, can be overridden per request
  credentials: {
    method: CredentialsMethod.ClientCredentials,
    config: {
      apiTokenIssuer: process.env.FGA_API_TOKEN_ISSUER,
      apiAudience: process.env.FGA_API_AUDIENCE,
      clientId: process.env.FGA_CLIENT_ID,
      clientSecret: process.env.FGA_CLIENT_SECRET,
    }
  }
});
```

### Expectation

See above

### Reproduction

See above

### SDK Checklist

- [ ] JS SDK
- [ ] Go SDK
- [ ] .NET SDK
- [ ] Python SDK
- [ ] Java SDK

### OpenFGA SDK version

0.6.1

### OpenFGA version

N/A

### SDK Configuration

N/A

**Comment by kanumalivad** [comment]
Hi @ryanpq Assign this to me.

**Comment by mohit07dec** [comment]
@ryanpq @rhamzeh Could you please assign it to me ?

**Comment by ewanharris** [comment]
I going to assign this to @kanumalivad as he commented first.

@mohit07dec if you're still interested in contributing #276 might be a good one to pick up

**Comment by siiddhantt** [comment]
hi @ewanharris I've linked a PR that should close this issue. Thanks!

**Comment by ewanharris** [comment]
My apologies @kanumalivad, I completely overlooked that we had assigned this to yourself.

If you're still interested in contributing I would recommend #276 as a good one.
