### ISSUE TITLE
Typo fix and Improve readability

### ISSUE THREAD

**Issue by tmsagarofficial** [openfga/sdk-generator#425]
I would want to let you know that in the docs of the repo `js-sdk`  I've found some typos and some phrases that can help the documentation be clearer and readable to the users.

Pls, assign this issue to me so that I can work on the same. Under hacktoberfest.

**Comment by ewanharris** [comment]
Thanks @tmsagarofficial! I've assigned this issue.

Just a heads up that we've merged #422 and #424 but just haven't ported them to the individual SDKs yet.

**Comment by tmsagarofficial** [comment]
Ohh ok, Thanks for the heads up @ewanharris .

**Comment by tmsagarofficial** [comment]
Check this out https://github.com/openfga/js-sdk/pull/164 @ewanharris
