### ISSUE TITLE
Links broken in CONTRIBUTING.md

### ISSUE THREAD

**Issue by DesignrKnight** [openfga/sdk-generator#47]
Hello, I was navigating the project and I encountered that the link to the sdk-generator is broken in CONTRIBUTING.md
The present link takes to: https://github.com/openfga/sd-generator
whereas the actual link is https://github.com/openfga/sdk-generator

It is a small typo but it would be fantastic to fix it. 

Additionally, I also found that the link for CODE_OF_CONDUCT redirects to: https://github.com/openfga/rfcs/blob/main/CODE-OF-CONDUCT.md which also gives 404

**Comment by adriantam** [comment]
@DesignrKnight - thank you for raising the issue. It looks like the links are in https://github.com/openfga/sdk-generator/blob/85cffdb0393b3ffb51e14b70e01e14d7be3a4557/config/common/files/CONTRIBUTING.md.mustache#L26 and https://github.com/openfga/sdk-generator/blob/85cffdb0393b3ffb51e14b70e01e14d7be3a4557/config/common/files/CONTRIBUTING.md.mustache#L20.
