### ISSUE TITLE
[All SDKs] support read-tuples endpoint

### ISSUE THREAD

**Issue by dabdada** [openfga/sdk-generator#74]
In the OpenFGA documentation there is also an endpoint `stores/{id}/read-tuples` to list all currently existing tuples in the store. 

As for read requests an object is required, I did not find a way to call the read-tuples endpoint via the sdk.

Please add support for this endpoint.

https://openfga.dev/api/service#/Relationship%20Tuples/ReadTuples

**Comment by dabdada** [comment]
Hi @rhamzeh 

thanks for your response. This makes a lot of sense thanks a lot 👍🏻

**Comment by rhamzeh** [comment]
FYI: `ReadTuples` was deprecated and Read was extended to support that use-case in https://github.com/openfga/openfga/releases/tag/v0.3.0
`ReadTuples` was fully removed in https://github.com/openfga/openfga/releases/tag/v0.3.4

So closing this issue. Let us know if your use-case isn't covered @dabdada

**Comment by dabdada** [comment]
Amazing thanks a lot for all your work. This is more than suitable and works pretty good ❤️
